// packages/create-vite/template-react/Source/App.jsx
import { useState } from "react";

import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";

import "./App.css";

function App() {
	const [count, setCount] = useState(0);

	return (
		<>
			<div>
				<a href="https://vitejs.dev" target="_blank">
					<img src={viteLogo} className="logo" alt="Vite logo" />
				</a>
				<a href="https://react.dev" target="_blank">
					<img
						src={reactLogo}
						className="logo react"
						alt="React logo"
					/>
				</a>
			</div>
			<h1>Vite + React</h1>
			<div className="card">
				<button onClick={() => setCount((count) => count + 1)}>
					count is {count}
				</button>
				<p>
					Edit <code>src/App.jsx</code> and save to test HMR
				</p>
			</div>
			<p className="read-the-docs">
				Click on the Vite and React logos to learn more
			</p>
		</>
	);
}

export default App;

// packages/create-vite/template-qwik/Source/app.jsx
import { component$, useSignal } from "@builder.io/qwik";

import qwikLogo from "./assets/qwik.svg";
import viteLogo from "/vite.svg";

import "./app.css";

export const App = component$(() => {
	const count = useSignal(0);

	return (
		<>
			<div>
				<a href="https://vitejs.dev" target="_blank">
					<img src={viteLogo} class="logo" alt="Vite logo" />
				</a>
				<a href="https://qwik.builder.io" target="_blank">
					<img src={qwikLogo} class="logo qwik" alt="Qwik logo" />
				</a>
			</div>
			<h1>Vite + Qwik</h1>
			<div class="card">
				<button onClick$={() => count.value++}>
					count is {count.value}
				</button>
				<p>
					Edit <code>src/app.jsx</code> and save to test HMR
				</p>
			</div>
			<p class="read-the-docs">
				Click on the Vite and Qwik logos to learn more
			</p>
		</>
	);
});
